go_import_path: github.com/kevinburke/ssh_config

language: go

os: linux
dist: trusty

sudo: required

before_script:
  - make install-travis

script:
  - make ci

cache:
  directories:
    - $HOME/.bzrepos
